Arsenic-ATG/Emacs-config

readme.org
Line 24: Typo corrected form  initialisations to initializations
=> Typo Corrected in readme.org

elisp/init-expand-region.el, init.el
=> New-package: expand region

elisp/init-org.el
improve strup performace of emacs
fix #14
=> Org: defer org tempo after org mode

elisp/init-org.el
org noter to takes note effectively from pdf files
close #29
=> New-package: Org noter

elisp/init-global-config.el
=> global-config: unbind s-w

elisp/init-theme.el
=> Doom modeline: Remove minor modes from the modeline

elisp/init-dired.el
=> dired: defer dired-single after dired

elisp/init-dired.el
=> dired-hacks: add dired-rainbow

elisp/init-format.el
The config file should have been staged and added on commit 2ed6ec78fb3c4aebf2ba8b0a9133e706cf1a5578
close #42 on GitHub
=> fix: No such file or directory, init-format

elisp/init-org.el
=> org-noter: defer on "org-noter" command

themes/Arsenic-flate-theme.el, themes/doom-flate-theme.el
Arsenic flate is like development version of doom-flate theme, the theme is currently work in progress.
=> Theme: add arsenic-flate and doom-flate

themes/Arsenic-flate-theme.el
- change magit and dashbord to look more pleasing to eyes
- close #54 #55
=> Theme: change magit and dashboard colors

themes/Arsenic-flate-theme.el
- Fix colors of which key minibuffer
- reorder all the section in alphabetical order
- close #59
=> Theme: which-key coloring and reordering sections

elisp/init-dired.el, themes/Arsenic-flate-theme.el
- reduce the colors in rainbow dired configuration ( a lot them was removing the cause of adding the colors at the first place )
- make rainbow dired align with flate
- change color of dired header in flate theme
- close #51
=> dired: make rainbow dired align with flate

elisp/init-beacon.el, elisp/init-theme.el, init.el
- create init-beacon.el
- use highlight color for beacon instead of static color
- close #64
=> beacon: seperate configuration in seperate file

elisp/init-dired.el
- add buffer list mode to global-auto-revert-ignored-modes
- fix #66 on GitHub
=> dired: fix auto-refreshing issue with buffer list

elisp/init-cc.el
- use cmake mode to highlight and indent cmake files
- close #61
=> cc: Add cmake mode

.gitignore
=> Create .gitignore files

elisp/init-lsp.el, init.el
=> lsp: set up lsp configuration

elisp/init-webdev.el, init.el
- configure web-mode for basic web-development
- fix #79 on GitHub
=> web-mode: new package configuration

elisp/init-tab-bar.el
- Fix #82 on GitHub.
- Use alternative variables to disable new button and close button.
=> tab-bar: Use alternate way to customize tab-bar

elisp/init-syntax.el
=> syntax: set flycheck C++ standard to 20

elisp/init-package.el
=> new-package: configure exec-path-from-shell package

readme.org
- Add info about Emacs-plus
- Update the required Emacs version ( for tab-bar-mode )
- fix minor typos and formatting errors.
=> Readme: add info about xwidgets support

elisp/init-ui-config.el
=> ui-config: change cursor to bar type

elisp/init-irc.el, init.el
- add configuration of in-built ERC mode of Emacs
- close #96
=> new-package: configure ERC mode

elisp/init-irc.el
=> IRC: fix file name in comments

elisp/init-dired.el
configure dired-collapse and dired-subtree from dired hacks
close: #101 #100 #39
=> dired: configure dired-collapse and dired-subtree

elisp/init-rainbow.el, init.el
rainbow mode to inline color the color hex values in buffers
- close #98
=> new-package: rainbow mode

elisp/init-lsp.el
=> lsp: disable lsp for C and Cpp mode

elisp/init-webdev.el
=> web-mode: disable auto indentation

init.el
=> temp: disable golden ratio mode

elisp/init-ui-config.el
=> Fix: disable line number mode on xwidget-webkit-mode

elisp/init-dired.el
- Remove dired-single package ( fix #138 on Github)
- Use `dired-kill-when-opening-new-dired-buffer`
- change default command to "ls" instead of "gls" ( "gls" was set for my macOS specific configuration )
=> dired: Remove dired-single
